/* A second way to read captions.
 *
 * The library the app normally uses reads YouTube as the Android client, and
 * some hosts are refused there — the player answers without caption tracks at
 * all. This path asks as a different Innertube client (whatever youtubei.js
 * negotiates, web by default), which is a different question to YouTube's bot
 * checks than the one that was declined. It carries no proof-of-origin token, so
 * it is not a fix for a blocked address; it is a second attempt from a different
 * angle, and it reports which angle answered.
 *
 * Its item shape is converted to the one the rest of the app expects: text plus
 * offset and duration in SECONDS, matching youtube-transcript-plus.
 */
const PREFERRED_LANGS = ['en', 'en-US', 'en-GB', 'en-IN', 'en-AU', 'en-CA']

let sessionPromise = null

function session() {
    // One session for the process: creating it fetches visitor data, and
    // repeating that per video would be a request for nothing.
    if (!sessionPromise) {
        sessionPromise = (async () => {
            const { Innertube } = require('youtubei.js')
            // The player response is where caption tracks live, so it must be
            // requested — the default, and the reason this is not turned off.
            return Innertube.create({ generate_session_locally: true })
        })().catch((err) => {
            sessionPromise = null
            throw err
        })
    }
    return sessionPromise
}

function pickTrack(tracks) {
    if (!Array.isArray(tracks) || tracks.length === 0) return null
    for (const lang of PREFERRED_LANGS) {
        const written = tracks.find((t) => t.language_code === lang && t.kind !== 'asr')
        if (written) return written
    }
    for (const lang of PREFERRED_LANGS) {
        const auto = tracks.find((t) => t.language_code === lang)
        if (auto) return auto
    }
    return tracks[0]
}

async function readCaptionsViaInnertube(videoId) {
    if (!videoId) {
        return { ok: false, reason: 'no-video-id' }
    }

    try {
        const yt = await session()
        const info = await yt.getInfo(videoId)
        const track = pickTrack(info.captions?.caption_tracks)
        if (!track?.base_url) {
            return { ok: false, reason: 'no-tracks' }
        }

        // json3 is the same timed text the library parses, in one object.
        const response = await fetch(`${track.base_url}&fmt=json3`)
        if (!response.ok) {
            return { ok: false, reason: `timedtext-${response.status}` }
        }

        const body = await response.json()
        const items = (body.events || [])
            .filter((event) => Array.isArray(event.segs) && event.dDurationMs > 0)
            .map((event) => ({
                text: event.segs.map((segment) => segment.utf8).join(''),
                offset: (event.tStartMs || 0) / 1000,
                duration: (event.dDurationMs || 0) / 1000,
            }))

        if (items.length === 0) {
            return { ok: false, reason: 'empty-transcript' }
        }

        return {
            ok: true,
            items,
            track: { languageCode: track.language_code, isAutoGenerated: track.kind === 'asr' },
        }
    } catch (err) {
        return { ok: false, reason: err?.name || 'Error', message: err?.message }
    }
}

module.exports = { readCaptionsViaInnertube }
