const { fetchTranscript, listLanguages } = require('youtube-transcript-plus')
const { AiError } = require('./aiService')
const { DEFAULT_PARAGRAPH_MS, decodeHtmlEntities, mergeSegmentsByDuration, sanitizeText } = require('../utils/transcript')

// Summarize, then Ask, then Notes, then Quiz all need the SAME transcript for
// one video, and each call would otherwise re-download it from YouTube. A short
// cache removes that repeat, and keeps YouTube off the critical path for every
// request after the first.
const CACHE_TTL_MS = 15 * 60 * 1000
const CACHE_MAX_ENTRIES = 50
const cache = new Map()

function cacheGet(videoId){
    const hit = cache.get(videoId)
    if(!hit) return null
    if(Date.now() > hit.expires){
        cache.delete(videoId)
        return null
    }
    return hit.data
}

function cacheSet(videoId, data){
    // Plain Map iteration order is insertion order, so the oldest key is first.
    if(cache.size >= CACHE_MAX_ENTRIES){
        const oldest = cache.keys().next().value
        if(oldest !== undefined) cache.delete(oldest)
    }
    cache.set(videoId, { data, expires: Date.now() + CACHE_TTL_MS })
}

// Which caption track to read. YouTube lists a video's tracks in its own order,
// and that order is not always the video's own language: an English video whose
// first track is an automatic translation would otherwise be summarized in that
// language. So a human-written English track wins, then an automatic English
// one, then English regional variants, and only then whatever the video has.
const PREFERRED_LANGS = ['en', 'en-US', 'en-GB', 'en-IN', 'en-AU', 'en-CA']

function pickTrack(tracks){
    if(!Array.isArray(tracks) || tracks.length === 0){
        return null
    }
    for(const lang of PREFERRED_LANGS){
        const written = tracks.find(track => track.languageCode === lang && !track.isAutoGenerated)
        if(written) return written
    }
    for(const lang of PREFERRED_LANGS){
        const auto = tracks.find(track => track.languageCode === lang)
        if(auto) return auto
    }
    return tracks[0]
}

/* "This video has no captions" and "YouTube would not talk to us" look the same
   to the visitor but only one of them is worth retrying, so they are separated
   here: the first is a 404 the caller answers with, the second is ours. */
const NO_CAPTIONS = new Set([
    'YoutubeTranscriptDisabledError',
    'YoutubeTranscriptNotAvailableError',
    'YoutubeTranscriptVideoUnavailableError',
    'YoutubeTranscriptInvalidVideoIdError',
])

async function fetchRawTranscript(videoId){
    if(!videoId){
        return null
    }

    let track
    try{
        // Reading the track list first is what makes the choice above possible.
        track = pickTrack(await listLanguages(videoId))
        if(!track){
            return null
        }
        // youtube-transcript-plus solves YouTube's PoToken requirement, which
        // makes the older youtube-transcript package return empty results.
        return await fetchTranscript(videoId, { lang: track.languageCode })
    }catch(err){
        const name = err?.name || 'Error'

        if(NO_CAPTIONS.has(name)){
            return null
        }

        // The operator gets the numbers; the visitor gets one plain sentence.
        console.warn(`[transcript] ${videoId} unavailable: ${name}: ${err?.message || err}`)
        throw new AiError(
            "We couldn't read this video's captions right now. Please try again in a few minutes.",
            { status: 503, code: 'TRANSCRIPT_UNAVAILABLE' }
        )
    }
}

// Full clean text + timed segments in a single fetch (used by the summary flow).
async function getTranscriptData(videoId){
    if(!videoId){
        return null
    }

    const cached = cacheGet(videoId)
    if(cached) return cached

    const transcript = await fetchRawTranscript(videoId)

    if(!transcript || transcript.length === 0){
        return null
    }

    // Segment offset/duration are in SECONDS; convert to ms for the API.
    const captionLines = transcript
        .map(item => ({
            text: sanitizeText(decodeHtmlEntities(item.text)),
            offsetMs: Math.round((item.offset || 0) * 1000),
            durationMs: Math.round((item.duration || 0) * 1000)
        }))
        .filter(segment => segment.text)

    if(captionLines.length === 0){
        return null
    }

    const segments = mergeSegmentsByDuration(captionLines, DEFAULT_PARAGRAPH_MS)
    const text = sanitizeText(segments.map(segment => segment.text).join(' '))

    const data = { text, segments }
    cacheSet(videoId, data)
    return data
}

async function getTranscriptByVideoId(videoId){
    const data = await getTranscriptData(videoId);
    return data ? data.text : null;
}

async function getTimedSegments(videoId){
    const data = await getTranscriptData(videoId);
    return data ? data.segments : null;
}

module.exports = { getTranscriptByVideoId, getTimedSegments, getTranscriptData }
